/**
 * Civilization IDs from the aoe2lobby.com WebSocket schema.
 * Keep this aligned with their `schema.civilization` map, not the Relic race IDs.
 */

export const CIV_NAMES: Record<number, string> = {
  0: "Hidden",
  1: "Britons",
  2: "Franks",
  3: "Goths",
  4: "Teutons",
  5: "Japanese",
  6: "Chinese",
  7: "Byzantines",
  8: "Persians",
  9: "Saracens",
  10: "Turks",
  11: "Vikings",
  12: "Mongols",
  13: "Celts",
  14: "Spanish",
  15: "Aztecs",
  16: "Mayans",
  17: "Huns",
  18: "Koreans",
  19: "Italians",
  20: "Hindustanis",
  21: "Incas",
  22: "Magyars",
  23: "Slavs",
  24: "Portuguese",
  25: "Ethiopians",
  26: "Malians",
  27: "Berbers",
  28: "Khmer",
  29: "Malay",
  30: "Burmese",
  31: "Vietnamese",
  32: "Bulgarians",
  33: "Tatars",
  34: "Cumans",
  35: "Lithuanians",
  36: "Burgundians",
  37: "Sicilians",
  38: "Poles",
  39: "Bohemians",
  40: "Dravidians",
  41: "Bengalis",
  42: "Gurjaras",
  43: "Romans",
  44: "Armenians",
  45: "Georgians",
  46: "Random",
  47: "Mirror",
  48: "Full Random",
  49: "Custom",
  50: "Egyptians",
  51: "Greeks",
  52: "Babylonians",
  53: "Assyrians",
  54: "Minoans",
  55: "Hittites",
  56: "Phoenicians",
  57: "Sumerians",
  58: "Old Persians",
  59: "Shang",
  60: "Yamato",
  61: "Choson",
  62: "Old Romans",
  63: "Carthaginians",
  64: "Palmyrans",
  65: "Macedonians",
  66: "Lac Viet",
  67: "Achaemenids",
  68: "Athenians",
  69: "Spartans",
  70: "Shu",
  71: "Wu",
  72: "Wei",
  73: "Jurchens",
  74: "Khitans",
  75: "Mapuche",
  76: "Muisca",
  77: "Tupi",
};

export function getCivName(id: number): string {
  return CIV_NAMES[id] ?? `Unknown (${id})`;
}

export const SERVER_REGIONS: Record<number, string> = {
  0: "Automatic",
  1: "US East",
  2: "US West",
  3: "Southeast Asia",
  4: "Australia",
  5: "South America",
  6: "Korea",
  7: "Europe West",
  8: "Europe East",
  9: "Middle East",
  10: "India",
  11: "Japan",
  12: "South Africa",
  13: "UK",
};
